### PR TITLE
Geopy 1287

### PR DESCRIPTION
**Pull request by MatthieuCMira**
**GEOPY-1229 - correct drillhole concatenated creation**
Change text bytes import into geoh5py

### CODE REVIEW

**Review by domfournier — COMMENTED** [review]
Looks good, but would be nice to have a unittest that shows this at work.

**Comment by MatthieuCMira** [comment]
It's covered by unitest no?

just the multi-text data is not covered.

**Comment by MatthieuCMira** [comment]
I added a asssert for values property and setter

**Review by domfournier — APPROVED** [review]
Fantastic.

**Pull request merged**
