### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RichardScottOZ**
Very basic usage

### CODE REVIEW

**Comment by domfournier** [comment]
Hi @RichardScottOZ , can you tell me more about your notebook? What kind of text can we add to describe the goal of the example?

**Comment by RichardScottOZ** [comment]
My idea is to have a notebook of examples of  - this is how you get data/information from a project that already exists - e.g. syntax to interface etc., as opposed to the make a new one synthetic variety.

**Comment by RichardScottOZ** [comment]
Just a skeleton currently.

**Comment by RichardScottOZ** [comment]
e.g. here's my geoscience analyst project, how do I grab stuff out of it to use elsewhere in standard python fashion

as opposed to the examples which are all take stuff from elsewhere and put into Analyst?

**Pull request closed without merging**
